done

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,40 +1,46 @@
 #!/usr/bin/env bash
+# script that installs the Nginx web server and configures the initial "Hello
+# world" page.
 
-# Configures a new Ubuntu machine by installing Nginx,
-# configuring it to listen on port 80, and serving a simple "Hello World" page.
+if [[ $EUID -ne 0 ]]; then
+	echo "ERROR: You need to be root" 1>&2
+	exit 1
+fi
 
-# Update package list and install Nginx
-echo -e "Updating and installing Nginx.\n"
-sudo apt-get update -y -qq && \
-sudo apt-get install nginx -y
+# Update the package list and install Nginx
+apt-get update
+apt-get install -y nginx
 
-echo -e "\nSetting up some minor stuff.\n"
+# Create the default "Hello world" page
+echo "Hello World!" > /var/www/html/index.html
+
+# configure error 404 page
+echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
+
+# confifure the server for redirection and 404 page
+echo -e "\tserver_name _;
+\tlocation /redirect_me {
+\t\treturn 301 https://drive.google.com/file/d/130vHZlceKje17SE9uPx8mAZWADVTs3XW/view?usp=sharing/;
+\t}
+
+\terror_page 404 /404.html;
+\tlocation = /404.html {
+\t\troot /usr/share/nginx/html;
+\t\tinternal;
+\t}
+" > /tmp/new_config
+
+sed -i '/server_name _;/{
+	r /tmp/new_config
+}' /etc/nginx/sites-available/default
+
+# Remove the temporary configuration file
+rm /tmp/new_config
 
 # Start the Nginx service
-sudo service nginx start
+service nginx restart
 
-# Allow Nginx through the firewall
-sudo ufw allow 'Nginx HTTP'
-
-# Give the user ownership of website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
-
-# Backup the default Nginx index file
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
-
-# Create a new index file with a "Hello World!" message
-echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
-
-# Set up a redirection rule for /redirect_me to a YouTube video
-sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
-
-# Set up a custom 404 page
-echo "Ceci n'est pas une page" > /var/www/html/error_404.html
-sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
-
-# Restart Nginx to apply the changes
-sudo service nginx restart
-
-# Display completion message
-echo -e "\nCompleted.\n"
+if [[ ! $? ]]; then
+	echo "ERROR: Failed to restart Nginx" 1>&2
+	exit 1
+fi
