revised

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,56 +1,88 @@
 #!/usr/bin/env bash
-# install load balancer
+# script that installs and configures the HAproxy load balancer. It configures
+# the server to send traffic to two web servers. The load balanceing algorithm
+# is round-robin.
 
-echo -e "Updating and doing some minor checks...\n"
+# Define variables for web server IP addresses
+WEB_SERVER_1_IP="34.224.62.190"
+WEB_SERVER_2_IP="34.239.253.87"
 
-function install() {
-    command -v "$1" &> /dev/null
+# Add entries to /etc/hosts
+echo "$WEB_SERVER_1_IP web-01.emyjakarta.tech" >> /etc/hosts
+echo "$WEB_SERVER_2_IP web-02.emyjakarta.tech" >> /etc/hosts
 
-    # shellcheck disable=SC2181
-    if [ $? -ne 0 ]; then
-        echo -e "    Installing: $1\n"
-        sudo apt-get update -y -qq && \
-            sudo apt-get install -y "$1" -qq
-        echo -e "\n"
-    else
-        echo -e "    ${1} is already installed.\n"
-    fi
+# Function to resolve IP address from hostname
+resolve_ip() {
+	hostname=$1
+	ip=$(dig +short $hostname)
+	echo "$ip"
 }
 
-# Install haproxy
-install haproxy
+# Configuration for HAProxy
+config="
+frontend emyjakarta_frontend
+	bind *:80
+	mode http
+	default_backend emyjakarta_backend
 
-echo -e "\nSetting up some minor stuff.\n"
-
-# Backup the default haproxy configuration file
-sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
-
-# Define haproxy server configuration
-haproxy_config="
-defaults
-  mode http
-  timeout client 15s
-  timeout connect 10s
-  timeout server 15s
-  timeout http-request 10s
-frontend clickviral-tech-frontend
-    bind *:80
-    default_backend clickviral-tech-backend
-backend clickviral-tech-backend
-    balance roundrobin
-    server 436533-web-01 54.227.199.4:80 check
-    server 436533-web-02 100.25.203.163:80 check
+backend emyjakarta_backend
+	balance roundrobin
+	server 527465-web-01 $(resolve_ip web-01.emyjakarta.tech):80 check
+	server 527465-web-02 $(resolve_ip web-02.emyjakarta.tech):80 check
 "
+# Check if the user is root
+if [ $EUID -ne 0 ]; then
+	echo "You must be root"
+	exit 1
+fi
 
-# shellcheck disable=SC2154
-echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
+function add_config() {
+	# let's do some house checking first, ensure the configuration does not 
+	# exist before we append to it
+	grep -q -e "emyjakarta_frontend" -e "emyjakarta_backend" /etc/haproxy/haproxy.cfg
 
-# Enable haproxy to be started by the init script
-echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
+	status=$?
+	if [[ $status -ne 0 ]]; then
+		# configure HAproxy
+		echo "$config" >> /etc/haproxy/haproxy.cfg
+	else
+		echo "Configuration already exists."
+		exit
+	fi
 
-# Check if haproxy is running and start/restart accordingly
-if [ "$(pgrep -c haproxy)" -le 0 ]; then
-    sudo service haproxy start
+	grep -q "ENABLED" /etc/default/haproxy
+
+	status=$?
+	if [[ $status -ne 0 ]]; then
+		echo "ENABLED=1" >> /etc/default/haproxy
+	fi
+
+	# restart HAproxy
+	service haproxy restart
+}
+
+# let's save time and check if the HAproxy package is already installed
+which haproxy > /dev/null
+
+status=$?
+if [[ $status -ne 0 ]]; then
+	# update package list
+	apt-get update -y
+
+	# enable dedicated PPA for HAproxy 2.8
+	apt-get install --no-install-recommends -y software-properties-common
+	add-apt-repository -y ppa:vbernat/haproxy-2.8
+
+	# install HAproxy
+	apt-get install -y haproxy
+
+	if [[ ! $? ]]; then
+		echo "Failed to install HAproxy."
+		exit 1
+	fi
+
+	add_config
 else
-    sudo service haproxy restart
+	# HAproxy is already installed, just add the configuration
+	add_config
 fi
